### ISSUE TITLE
Model merging leads to segmentation faults

### ISSUE THREAD

**Issue by simleo** [deephealthproject/eddl#190]
In the current develop branch, the `mnist_auto_encoder_merging` example breaks with a segmentation fault:

```
./build/bin/mnist_auto_merging
[...]
Generating Random Table
Building model
Segmentation fault (core dumped)
```

In eddl 0.6.0 the example runs fine, but only because there are no deletes. Deleting the merged net and one of the components leads to segmentation faults. E.g.:

```cpp
#include <eddl/apis/eddl.h>

using namespace eddl;

int main() {
    layer in = Input({784});
    layer l = in;
    l = Activation(Dense(l, 256), "relu");
    layer out = Activation(Dense(l, 64), "relu");
    model m1 = Model({in}, {out});

    in = Input({64});
    l = Activation(Dense(in, 128), "relu");
    out = Sigmoid(Dense(l, 784));
    model m2 = Model({in}, {out});

    model merged = Model({m1, m2});

    build(merged,
          adam(0.0001),
          {"mse"},
          {"dice"},
          CS_GPU({1}));

    delete merged;                                                           
    delete m1;                                                               
}
```

This breaks any pyeddl program that tries to use the model merging function.

Things seem to be even worse in the current develop branch, since the program segfaults even with no deletes at all (as seen above for the original example).

**Comment by RParedesPalacios** [comment]
Yes I am aware will be fixed soon

**Comment by RParedesPalacios** [comment]
Fixed, please check to within the new Master version

**Comment by simleo** [comment]
I still get a segmentation fault after deleting the models. Checked with [current master](https://github.com/deephealthproject/eddl/tree/78e2177d22d78b3298b059adce37a48d93ee648c), with the same code as above, only difference is that I'm using a `CS_CPU()`. Switching the order of `delete merged` and `delete m1` makes no difference, but if I delete only one of them it does not segfault.

**Comment by RParedesPalacios** [comment]
Simone ok i will recheck that, thanks

**Comment by RParedesPalacios** [comment]
We have checked together with Simone. Now in develop branch is solved. I close this.
