### ISSUE TITLE
Protobuf path

### ISSUE THREAD

**Issue by salvacarrion** [deephealthproject/eddl#206]
When using `-D BUILD_SUPERBUILD=ON`, the location of the library changes. Sometimes it is on `cmake/third_party/protobuf/lib/libprotobuf.a` and others on `cmake/third_party/protobuf/lib64/libprotobuf.a `.

While we're solving this issue, **a workaround is to use a symbolic link:** `ln -s lib64/ lib/`

**Comment by jonandergomez** [comment]
Salva, if this is already solved, could you close this issue?

Thanks in advance.

**Comment by salvacarrion** [comment]
It is not fully fixed since I'm not 100% when protobuf is using lib/ or lib64/
